### ISSUE TITLE
2018/9 Gold Summary

### ISSUE THREAD

**Issue by Saichethan** [WING-NUS/scisumm-corpus#15]
Where can I find gold summaries for 2018/9 test dataset?

**Comment by cmkumar87** [comment]
Thanks for your enquiry! The Gold standard summaries for the most recent test set are blind since we are still actively running this shared task. We encourage you to register for this year's shared task. https://ornlcda.github.io/SDProc/clscisumm.html#clscisumm We will send the CfP on Feb 15. Please watch this space.
