### ISSUE TITLE
data corruption in J96-3004.xml

### ISSUE THREAD

**Issue by jungokasai** [WING-NUS/scisumm-corpus#7]
Hi, I just found that [one example in Training Set 2017](https://github.com/WING-NUS/scisumm-corpus/blob/master/data/Training-Set-2017/J96-3004/Reference_XML/J96-3004.xml) is not properly assigned sids for the abstract.

**Comment by cmkumar87** [comment]
@jungokasai  I confirm that the abstract of the said training file does not have sids assigned for the Abstract section. Thanks for the report!

However, it is inconsequential since none of the annotated reference spans are from the Abstract section. In other words, all the annotated references spans here: https://github.com/WING-NUS/scisumm-corpus/blob/master/data/Training-Set-2017/J96-3004/annotation/J96-3004.ann.txt have an sid assigned.
Please let us know if you find it otherwise.

**Comment by jungokasai** [comment]
Right, thank you for your quick response!
